language: python

matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: DJANGO=1.11
    - python: "3.5"
      env: DJANGO=2.0
    - python: "3.5"
      env: DJANGO=2.1
    - python: "3.5"
      env: DJANGO=master

    - python: "3.6"
      env: DJANGO=1.11
    - python: "3.6"
      env: DJANGO=2.0
    - python: "3.6"
      env: DJANGO=2.1
    - python: "3.6"
      env: DJANGO=master
    - python: "3.6"
      env: TOXENV=lint

    - python: "3.7-dev"
      env: DJANGO=2.0
    - python: "3.7-dev"
      env: DJANGO=2.1
    - python: "3.7-dev"
      env: DJANGO=master

  allow_failures:
    - env: DJANGO=master

addons:
  apt:
    packages:
     - enchant

install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox

after_success:
  - codecov -e TOXENV,DJANGO

notifications:
  email: false
  slack: 
    rooms:
      - browniebroke:Nhh14UnAYVVhQu06NlveBdWh
    on_success: change
    on_failure: always

deploy:
  provider: pypi
  user: "Bruno.Alla"
  password:
    secure: P2eYYTKXZD8GFYKPSwKwOvwn7+p+6ZemL2REwdKxGO7PRGIimj+iAWrwgfMajWXkv8TSLr1+QgXUonCwxBqfZjHTXtHtsCKygrK7t375faNxck66NVj3KJ/vXMTWEPXAH0yp/1jGy1gJ3fm2+eo1taHnp7AuaNIshZ7VrZ+57hSeZPWfI2e0l2Etr8iFLLBMFIZ7tRzESLZAg5J3HeigmsfEbu5qLQ/xcw0FQF7eEEG3iAAA0jGflxTALxXjWDgMQgGTtXC9Ft4zQlNZ6TaTw0Fkmo/3L90Kvm+UouHjnYz+QSczfUFHo62ResoBb0XhVYMDQ4VikpkY5l9qpUJeaR2myNu9x41DHDRTf0/2rnLJP6zOLhJ4Bs3tMqa/LiQ+dr0tVHm16Kn5Jg9OAPHGqKpEwJAV3T/tw+MtZKtZtcaLX/EgjXdFTxYvGwxHtYQsvPHm1sWUvY2YUjDg24q1f3aSMIp0BDDeB3gXQThfCYOX8HzorVVsAMAxRoUXwJzv3P18GH70+EnjvMfLryWIXPT7hYNjCb38BTLuU13IGqGQkU34+iHcpSZrhTuOf+y+DZKR3FpVLRHXJojpR00H8B/64jhadE7jNOpt0xgGy5/tu3wyT35kRZ9HbwVnbchBgyn30VRxpFj+yiGt7yPraawUch3RZpKO6krriA8RPGM=
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true
    python: 3.6
    condition: "$DJANGO = 2.0"
